# Imports

In [1]:
import pandas as pd
import litellm
from dotenv import load_dotenv
from datasets import load_dataset
from tqdm import tqdm
import os
import asyncio

In [2]:
# Load environment variables from .env file
load_dotenv()

True

In [3]:
# set callbacks
litellm.success_callback = ["langfuse"]
litellm.failure_callback = ["langfuse"]

# Load data

In [4]:
# Load the revised dataset
data_revised = pd.read_csv('data/AWAL evaluation sets - FLORES devtest (REVISED).csv')

data_revised["ID"] = data_revised.index

# remove unnecessary columns
data_revised = data_revised[["ID", "English", "Tamazight (Corrected)"]]
data_revised.columns = ["ID", "eng", "zgh"]

data_revised.describe(include='all')

,ID,eng,zgh
count,1012.000000,1012,1012
unique,NaN,1012,1012
top,NaN,Workers must often get their superiors' approv...,ⵉⴳⴳⵓⴷⵉ ⵎⴰ ⴳ ⴷ ⵉⵇⵇⴰⵏ ⴰⴷ ⵢⵉⵍⵉ ⵓⵎⵙⴰⵙⴰ ⵏ ⵉⵏⵙⵙⵉⵅⴼⵏ ...
freq,NaN,1,1
mean,505.500000,NaN,NaN
std,292.283538,NaN,NaN
min,0.000000,NaN,NaN
25%,252.750000,NaN,NaN
50%,505.500000,NaN,NaN
75%,758.250000,NaN,NaN
max,1011.000000,NaN,NaN

In [5]:
# Load the original dataset
eng_data_original = load_dataset("openlanguagedata/flores_plus", "eng_Latn", split="devtest")
zgh_data_original = load_dataset("openlanguagedata/flores_plus", "zgh_Tfng", split="devtest")

data_original = pd.DataFrame({
    "ID": eng_data_original["id"],
    "eng": eng_data_original["text"],
    "zgh": zgh_data_original["text"],
})

data_original.describe(include='all')

Resolving data files:   0%|          | 0/220 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/214 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/220 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/214 [00:00<?, ?it/s]

,ID,eng,zgh
count,1012.000000,1012,1012
unique,NaN,1012,1012
top,NaN,Workers must often get their superiors' approv...,ⵉⴳⴳⵓⵜ ⵎⴰⴳ ⴷ ⵉⵇⵇⴰⵏ ⴰⴷ ⵢⵉⵍⵉ ⵓⵎⵙⴰⵙⴰ ⵏ ⵉⵏⵙⵙⵉⵅⴼⵏ ⵏ ...
freq,NaN,1,1
mean,505.500000,NaN,NaN
std,292.283538,NaN,NaN
min,0.000000,NaN,NaN
25%,252.750000,NaN,NaN
50%,505.500000,NaN,NaN
75%,758.250000,NaN,NaN
max,1011.000000,NaN,NaN

In [6]:
# sanity check
assert data_original['eng'].equals(data_revised['eng']), "English texts do not match!"
assert not data_original['zgh'].equals(data_revised['zgh']), "Revised and original Tamazight texts should not match!"

# Preprocess data

In [7]:
# replace the 'ⵒ', 'ⵁ', and 'ⴴ' letters with 'ⴱ', 'ⵀ', and 'ⵖ' respectively, since they're not in the model's vocabulary
data_revised['zgh'] = data_revised['zgh'].str.replace('ⵒ', 'ⴱ')
data_revised['zgh'] = data_revised['zgh'].str.replace('ⵁ', 'ⵀ')
data_revised['zgh'] = data_revised['zgh'].str.replace('ⴴ', 'ⵖ')

data_original['zgh'] = data_original['zgh'].str.replace('ⵒ', 'ⴱ')
data_original['zgh'] = data_original['zgh'].str.replace('ⵁ', 'ⵀ')
data_original['zgh'] = data_original['zgh'].str.replace('ⴴ', 'ⵖ')

In [8]:
# this code is adapted from  the Stopes repo of the NLLB team
# https://github.com/facebookresearch/stopes/blob/main/stopes/pipelines/monolingual/monolingual_line_processor.py#L214

import re
import sys
import typing as tp
import unicodedata
from sacremoses import MosesPunctNormalizer


mpn = MosesPunctNormalizer(lang="en")
mpn.substitutions = [
    (re.compile(r), sub) for r, sub in mpn.substitutions
]


def get_non_printing_char_replacer(replace_by: str = " ") -> tp.Callable[[str], str]:
    non_printable_map = {
        ord(c): replace_by
        for c in (chr(i) for i in range(sys.maxunicode + 1))
        # same as \p{C} in perl
        # see https://www.unicode.org/reports/tr44/#General_Category_Values
        if unicodedata.category(c) in {"C", "Cc", "Cf", "Cs", "Co", "Cn"}
    }

    def replace_non_printing_char(line) -> str:
        return line.translate(non_printable_map)

    return replace_non_printing_char

replace_nonprint = get_non_printing_char_replacer(" ")

def preproc(text):
    clean = mpn.normalize(text)
    clean = replace_nonprint(clean)
    # replace 𝓕𝔯𝔞𝔫𝔠𝔢𝔰𝔠𝔞 by Francesca
    clean = unicodedata.normalize("NFKC", clean)
    return clean

In [9]:
# apply preprocessing
data_revised['eng'] = data_revised['eng'].apply(preproc)
data_revised['zgh'] = data_revised['zgh'].apply(preproc)

data_original['eng'] = data_original['eng'].apply(preproc)
data_original['zgh'] = data_original['zgh'].apply(preproc)

# Evaluation

In [10]:
lang_code_to_name = {
    "zgh": "Standard Moroccan Tamazight",
    "eng": "English"
}
lang_code_to_script = {
    "zgh": "Tifinagh",
    "eng": "Latin"
}

def translation_prompt(text, target_lang_code):
    target_lang_name = lang_code_to_name[target_lang_code]
    script = lang_code_to_script[target_lang_code]

    prompt = f"Translate the following text to the {target_lang_name} language; use the {script} script; reply only with the translation:\n\n{text}"

    return prompt

In [11]:
translation_prompt("Hello, how are you?", "zgh")

'Translate the following text to the Standard Moroccan Tamazight language; use the Tifinagh script; reply only with the translation:\n\nHello, how are you?'

In [12]:
translation_prompt("ⴰⵣⵓⵍ, ⵎⴰⵢ ⵜⵄⵏⵉⵜ?", "eng")

'Translate the following text to the English language; use the Latin script; reply only with the translation:\n\nⴰⵣⵓⵍ, ⵎⴰⵢ ⵜⵄⵏⵉⵜ?'

In [13]:
def get_llm_answers(data, model, source_lang_code, target_lang_code, resume_from=None, **kwargs):
    # Load previous answers if resume_from is provided
    if resume_from and os.path.exists(resume_from):
        print(f"Resuming from {resume_from}")
        previous_answers = pd.read_csv(resume_from)
        processed_ids = set(previous_answers['ID'].tolist())
        print(f"Found {len(processed_ids)} previously processed rows")
    else:
        previous_answers = pd.DataFrame(columns=['ID', 'prediction'])
        processed_ids = set()

    # Filter out rows that have already been processed
    data_to_process = data[~data['ID'].isin(processed_ids)]
    
    print(f"Processing {len(data_to_process)} new rows")
    
    new_answers = []
    for i, row in tqdm(data_to_process.iterrows(), total=len(data_to_process)):
        id = row["ID"]
        text = row[source_lang_code]
        prompt = translation_prompt(text, target_lang_code)
    
        try:
            response = litellm.completion(
                model=model,
                messages=[
                    {"role": "user", "content": prompt}
                    ],
                max_tokens=1024,
                **kwargs
            )
        except Exception as e:
            print(f"Error processing ID {id}: {e}")
            break

        # Extract the answer from the response
        answer = response["choices"][0]["message"]["content"]

        new_answers.append({
            "ID": id,
            "prediction": answer
        })
    
    # Create DataFrame from new answers and combine with previous answers
    if new_answers:
        new_answers_df = pd.DataFrame(new_answers)
        final_answers = pd.concat([previous_answers, new_answers_df], ignore_index=True)
        # Sort the final answers by ID
        final_answers.sort_values(by='ID', inplace=True)
    else:
        final_answers = previous_answers
    
    return final_answers


async def get_llm_answers_async(data, model, source_lang_code, target_lang_code, resume_from=None, max_in_flight_requests=5, **kwargs):
    # Load previous answers if resume_from is provided
    if resume_from and os.path.exists(resume_from):
        print(f"Resuming from {resume_from}")
        previous_answers = pd.read_csv(resume_from)
        processed_ids = set(previous_answers['ID'].tolist())
        print(f"Found {len(processed_ids)} previously processed rows")
    else:
        previous_answers = pd.DataFrame(columns=['ID', 'prediction'])
        processed_ids = set()

    # Filter out rows that have already been processed
    data_to_process = data[~data['ID'].isin(processed_ids)]
    
    print(f"Processing {len(data_to_process)} new rows")
    
    new_answers = []
    semaphore = asyncio.Semaphore(max_in_flight_requests)

    async def process_row(row):
        id = row["ID"]
        text = row[source_lang_code]
        prompt = translation_prompt(text, target_lang_code)

        async with semaphore:
            try:
                response = await litellm.acompletion(
                    model=model,
                    messages=[
                        {"role": "user", "content": prompt}
                    ],
                    max_tokens=1024,
                    **kwargs
                )
            except Exception as e:
                print(f"Error processing ID {id}: {e}")
                return None

            answer = response["choices"][0]["message"]["content"]
            return {"ID": id, "prediction": answer}

    tasks = [process_row(row) for _, row in data_to_process.iterrows()]
    results = await asyncio.gather(*tasks)

    for result in results:
        if result is not None:
            new_answers.append(result)

    # Create DataFrame from new answers and combine with previous answers
    if new_answers:
        new_answers_df = pd.DataFrame(new_answers)
        final_answers = pd.concat([previous_answers, new_answers_df], ignore_index=True)
        # Sort the final answers by ID
        final_answers.sort_values(by='ID', inplace=True)
    else:
        final_answers = previous_answers

    return final_answers

# ENG->ZGH

In [ ]:
# answers = get_llm_answers(data_revised, "gemini/gemini-2.5-pro", "eng", "zgh", resume_from="predictions/gemini-2.5-pro-eng-zgh-revised.csv", temperature=0.0, max_completion_tokens=25000, reasoning_effort="medium", num_retries=3)
answers = get_llm_answers(data_revised, "openrouter/google/gemini-2.5-pro", "eng", "zgh", temperature=0.0, max_completion_tokens=25000, num_retries=3)
answers

Processing 1012 new rows

 93%|█████████▎| 943/1012 [7:56:35<33:33, 29.18s/it]

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm._turn_on_debug()'.


Provider List: https://docs.litellm.ai/docs/providers

100%|██████████| 1012/1012 [8:30:53<00:00, 30.29s/it]

        ID                                         prediction
0        0  ⵢⴻⵔⵏⴰ: "ⵜⵓⵔⴰ ⵖⵓⵔ-ⵏⵖ ⵉⵖⴻⵔⴷⴰⵢⴻⵏ ⵏ 4 ⵏ ⵡⴰⵢⵢⵓⵔⴻⵏ ⵓ...
1        1  ⴷⵓⴽⵜⵓⵔ ⵉⵀⵓⴷ ⵓⵔ, ⴰⵙⵍⵎⴰⴷ ⵏ ⵜⵙⴳⵏⵉ ⴳ ⵜⴰⵙⴷⴰⵡⵉⵜ ⵏ ⴷⴰ...
2        2  ⴰⵎ ⴽⵔⴰ ⵏ ⵉⵎⵓⵙⵏⴰⵡⵏ ⵢⴰⴹⵏⵉⵏ، ⵉⵜⵜⵛⵓⴽⴽⵓ ⵉⵙ ⵢⴻⵣⵎⴻⵔ ⵓ...
3        3  ⴰⵙ ⵏ ⵡⴰⵢⵏⴰⵙ, ⵜⴱ𝑒ⵔⵔⵃ-ⴷ ⵙⴰⵔⴰ ⴷⴰⵏⵢⵓⵙ, ⵜⴰⵎⴰⵔⴰⵢⵜ ⵜⴰ...
4        4  ⵉⵏⵏⴰ ⴷⴰⵏⵉⵓⵙ: "ⵜⵓⵔⴰ, ⵓⵔ ⵏⵙⴽⴽⴰⵔ ⴽⵔⴰ. ⵙⵉⵡⵍⵖ ⴷ ⵓⵣⵏ...
...    ...                                                ...
1007  1007  ⵉⵎⵉ ⵜⵉⵎⵏⴰⴹⵉⵏ-ⴰⴷ ⵓⵔ ⵜⵜⵡⴰⵣⴷⴰⵖⴻⵏⵜ ⴰⵟⴰⵙ، ⴷⵖⴰ ⴰⵙⵔⴻⴳ...
1008  1008  ⵜⴰⴷⴰⵎⵙⴰ ⵏ ⵓⵅⴷⴷⵉⵎ ⵏ ⵊⵊⴰⴱⵓⵏ ⵜⴳⴰ ⵜⴰⵀⴰⵔⵔⴰⵎⵉⵜ ⵓ ⵜⴰⵏ...
1009  1009  ⵉⴽⵓⵙⵜⵓⵎⵏ ⴷ ⴰⵍⵙⵓ ⴰⵖⴰⵔⴰⵏ ⵏ ⵜⵖⴰⵡⵙⴰ، ⴷ ⵉⵎⴷⵓⴽⴽⴰⵍ ⵏ ...
1010  1010  ⵜⴰⵢⵎⴰⵜ ⴳ ⵓⵙⵡⵓⵔⵉ ⵜⴳⴰ ⵜⵉⵙⵓⵍⴰⵏⵜ, ⵜⵙⵎⵓⵔⵙ ⵅⴼ ⵓⵔⵎⵓⴷ ...
1011  1011  ⵖⴰⵍⵉⴱⴰⵏ, ⵉⵅⵚⵚⴰ ⴼ ⵉⵅⴷⴷⴰⵎⵏ ⴰⴷ ⴰⵎⵓⵏ ⴰⵣⵎⵣⵣⵓ ⵏ ⵉⵎⵙⵖ...

[1012 rows x 2 columns]

In [16]:
# save the answers to a CSV file
answers.to_csv("predictions/gemini-2.5-pro-eng-zgh-revised.csv", index=False)

In [ ]:
answers = await get_llm_answers_async(data_revised, "anthropic/claude-3-5-sonnet-20241022", "eng", "zgh", resume_from="predictions/claude-3.5-sonnet-20241022-eng-zgh-revised.csv", max_in_flight_requests=2, temperature=0.0, num_retries=2)
answers

Resuming from predictions/claude-3.5-sonnet-20241022-eng-zgh-revised.csv
Found 640 previously processed rows
Processing 372 new rows

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm._turn_on_debug()'.


Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm._turn_on_debug()'.


Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm._turn_on_debug()'.

        ID                                         prediction
0        0  ⵉⵏⵏⴰ: "ⴰⵖⵔⵉⵏ ⵉⵖⵔⴹⴰⵏ ⵏ 4 ⵡⴰⵢⵢⵓⵔⵏ ⵓⵔ ⴷⴰⵔⵙⵏ ⵜⴰⵎⴰⴹ...
1        1  ⴰⵎⵙⵙⵍⵎⴷ ⵉⵀⵓⴷ ⵓⵔ, ⴰⵎⵙⵙⵍⵎⴷ ⵏ ⵜⵙⵏⵓⵔⵉⵜ ⴷⵉ ⵜⵙⴷⴰⵡⵉⵜ ...
2        2  ⴰⵎ ⵉⵎⴰⵙⵙⵏⵏ ⵢⴰⴹⵏⵉⵏ, ⵓⵔ ⵢⵓⵎⵉⵏ ⵉⵙ ⵜⵣⵎⵔ ⵜⴰⵎⴰⴹⵓⵏⵜ ⵏ...
3        3  ⴳ ⵡⴰⵢⵢⵓⵔ, ⵙⴰⵔⴰ ⴷⴰⵏⵉⵓⵙ, ⵜⴰⵎⴰⵔⵉⵜ ⵜⴰⵎⵖⵍⴰⵍⵜ ⵏ ⵜⵙⵇⵇ...
4        4  ⵉⵏⵏⴰ ⴷⴰⵏⵉⵓⵙ: "ⵖⵉⵍⴰⴷ ⵓⵔ ⵏⵙⴽⴰⵔ ⵓⵍⴰ. ⵙⵙⵉⵡⵍⵖ ⴷ ⵓⵣⵏ...
...    ...                                                ...
636   1007  ⵍⵍⵉⴳ ⵜⴰⵎⵏⴰⴹⵜ ⵓⵔ ⵜⵣⴷⵖ ⵙ ⵡⴰⵜⵜⴰⵙ, ⴷ ⵜⵉⴼⴰⵡⵜ ⵏ ⵓⵙⵍⵓ...
637   1008  ⵜⴰⵎⵙⵙⵓⵔⵜ ⵏ ⵜⵡⵓⵔⵉ ⵜⴰⵊⴰⴱⴰⵏⵉⵜ ⵜⴻⵜⵜⵓⵙⵙⴰⵏ ⵙ ⵓⵙⵜⵜⵉ ⴷ...
638   1009  ⵜⴰⵎⵍⵙⴰ ⵏ ⵜⵙⵓⵜⵙ ⵜⴳⴰ ⵜⴰⵎⵍⵙⴰ ⵏ ⵜⵡⵓⵔⵉ, ⵉⵎⴰⵙⵙⵏ ⵏ ⵜⵡ...
639   1010  ⵜⴰⵎⵙⴰⵙⵜ ⴳ ⵜⵎⵙⵙⵓⵔⵜ ⵜⴳⴰ ⵜⴰⵎⵀⵎⵜ, ⵜⵙⵙⴽⵜⵉ ⵜⴰⵡⵓⵔⵉ ⵏ ...
1011  1011  ⵉⵎⵙⵡⵓⵔⵉⵏ ⵉⵅⵚⵚⴰ ⴰⴷ ⴰⵡⵉⵏ ⵜⵓⵔⴷⴰ ⵏ ⵉⵎⴰⵔⴰⵡⵏⵙⵏ ⵅⴼ ⵎⴰ...

[1012 rows x 2 columns]

In [18]:
# save the answers to a CSV file
answers.to_csv("predictions/claude-3.5-sonnet-20241022-eng-zgh-revised.csv", index=False)

In [14]:
answers = await get_llm_answers_async(data_revised, "anthropic/claude-3-7-sonnet-20250219", "eng", "zgh", max_in_flight_requests=2, max_completion_tokens=25000, reasoning_effort="medium", num_retries=2)
answers

Processing 1012 new rows

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm._turn_on_debug()'.

        ID                                         prediction
0        0  ⵖⵓⵔⵏⵖ ⵖⵉⵍⴰ ⵉⵖⵔⴷⴰⵢⵏ ⵉⵍⴰⵏ 4 ⵏ ⵉⵢⵢⵉⵔⵏ ⵓⵔ ⴷⴰⵔⵙⵏ ⵜⴰ...
1        1  ⴷⵔ. ⵉⵀⵓⴷ ⵓⵔ, ⴰⵙⵍⵎⴰⴷ ⵏ ⵜⵙⵏⵉⵜⵉⵎⵜ ⴷⵉ ⵜⵙⴷⴰⵡⵉⵜ ⵏ ⴷⴰ...
2        2  ⴰⵎ ⵉⵎⵙⵏⴰⵡⵏ ⵢⴰⴹⵏⵉⵏ, ⵢⴳⴰ ⴰⵎⵛⴽⴽⴰⴽ ⵅⴼ ⵉⵙ ⵜⵣⵎⵔ ⵜⴰⵣⵣ...
3        3  ⴰⵙⵙ ⵏ ⴰⵢⵏⴰⵙ, ⵙⴰⵔⴰ ⴷⴰⵏⵉⵓⵙ, ⵜⴰⵎⴰⵔⵉⵔⵜ ⵜⴰⵎⵖⵏⴰⵏⵜ ⵏ ...
4        4  ⵉⵏⵏⴰ ⴷⴰⵏⵉⵓⵙ, "ⵖⵉⵍⴰⴷ ⵓⵔ ⵏⵜⵜⴳⴳ ⴰⵎⵢⴰ. ⵙⵙⴰⵡⵍⵖ ⴷ ⵙⵙ...
...    ...                                                ...
1007  1007  ⵎⵉⵏⵣⵉ ⵜⵉⵎⵏⴰⴹⵉⵏ ⵓⵔ ⴷⴰⵢⵙⵏⵜ ⵎⴷⴷⵏ ⴰⵟⵟⴰⵙ, ⵉⵔⵉⴹⵉ ⵏ ⵜ...
1008  1008  ⵜⴰⴷⵍⵙⴰ ⵏ ⵜⵡⵓⵔⵉ ⵜⴰⵊⴰⴱⵓⵏⵉⵜ ⵜⴳⴰ ⴰⴽⵜⴰⵔ ⵜⴰⵎⵔⵜⴱⵜ ⴷ ⵜ...
1009  1009  ⵉⴱⴷⵍⴰⵜⵏ ⴳⴰⵏ ⴰⵔⵓⴷ ⴰⵏⴰⵎⵓⵔ ⵏ ⵜⵡⵓⵔⵉ, ⵉⵎⴷⵓⴽⴰⵍ ⵏ ⵜⵡⵓ...
1010  1010  ⴰⵎⵢⴰⵡⴰⵙ ⴳ ⵜⵡⵓⵔⵉ ⵉⵍⵍⴰ ⴷ ⴰⵎⵀⵉⵍ, ⵉⵙⴷⴷⴰⴷ ⴰⵎⵓⵏ ⵏ ⵜⴰ...
1011  1011  ⵉⵅⵙⵙⴰ ⵉ ⵉⵙⵎⵓⵏⵏ ⴰⴷ ⴰⵡⵙⵏ ⴰⴱⴹⴰ ⴰⵎⵏⵜⴰⵍ ⵏ ⵉⵏⵎⵀⴰⵍⵏ ⵏ...

[1012 rows x 2 columns]

In [15]:
# save the answers to a CSV file
answers.to_csv("predictions/claude-3.7-sonnet-20250219-eng-zgh-revised.csv", index=False)

# Revised data ZGH->ENG

In [14]:
answers = await get_llm_answers_async(data_revised, "openrouter/google/gemini-2.5-pro", "zgh", "eng", max_in_flight_requests=5, temperature=0.0, max_completion_tokens=25000, num_retries=2)
answers

Processing 1012 new rows

Unexpected error occurred. Please check your request and contact support: https://langfuse.com/support.

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm._turn_on_debug()'.

        ID                                         prediction
0        0  "We have here 4-month-old mice that have not b...
1        1  Dr. Ihud Ur, a professor of medicine at Dalhou...
2        2  Like some other researchers, he is skeptical a...
3        3  On Tuesday, Sara Danius, the permanent secreta...
4        4  Danyus said, "We don't do it that way here. I ...
...    ...                                                ...
1007  1007  When the population in the region is sparse an...
1008  1008  The Japanese work culture is more disciplined ...
1009  1009  Suits are the official attire of employers, an...
1010  1010  Collaboration is highly important in the workp...
1011  1011  It is often necessary that there be an agreeme...

[1012 rows x 2 columns]

In [15]:
# save the answers to a CSV file
answers.to_csv("predictions/gemini-2.5-pro-zgh-eng-revised.csv", index=False)

In [16]:
answers = await get_llm_answers_async(data_revised, "anthropic/claude-3-5-sonnet-20241022", "zgh", "eng", max_in_flight_requests=4, temperature=0.0, num_retries=2)
answers

Processing 1012 new rows

Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f51887a4d90>

        ID                                         prediction
0        0  "We now have 4-month-old mice that did not get...
1        1  Dr. Ehud Or, a professor of psychology at Dalh...
2        2  Like some other scientists, he was skeptical a...
3        3  On Tuesday, Sara Danius, the former permanent ...
4        4  Danyus said, "Now we don't do that anymore. I ...
...    ...                                                ...
1007  1007  When there are few inhabitants in the region, ...
1008  1008  The Japanese work culture is more disciplined ...
1009  1009  The suits are the official clothes of employer...
1010  1010  Teamwork is very important in the workplace, w...
1011  1011  It is necessary that there be agreement betwee...

[1012 rows x 2 columns]

In [17]:
# save the answers to a CSV file
answers.to_csv("predictions/claude-3.5-sonnet-20241022-zgh-eng-revised.csv", index=False)

In [20]:
answers = await get_llm_answers_async(data_revised, "anthropic/claude-3-7-sonnet-20250219", "zgh", "eng", resume_from="predictions/claude-3.7-sonnet-20250219-zgh-eng-revised.csv", max_in_flight_requests=3, max_completion_tokens=25000, reasoning_effort="medium", num_retries=2)
answers

Resuming from predictions/claude-3.7-sonnet-20250219-zgh-eng-revised.csv
Found 426 previously processed rows
Processing 586 new rows

        ID                                         prediction
0        0  "We now have 4-month-old mice that did not dev...
1        1  Dr. Ehud Ur, a professor of endocrinology at D...
2        2  Like some other researchers, he is skeptical a...
3        3  On Monday, Sara Danius, the permanent secretar...
4        4  Danyus said, "Now we don't do this anymore. I ...
...    ...                                                ...
424   1007  When there are few inhabitants in the region, ...
425   1008  Japanese work culture is more disciplined and ...
1009  1009  They wear formal suits as the official attire ...
1010  1010  Cooperation is very important in the workplace...
1011  1011  It is often necessary to have agreement betwee...

[1012 rows x 2 columns]

In [21]:
# save the answers to a CSV file
answers.to_csv("predictions/claude-3.7-sonnet-20250219-zgh-eng-revised.csv", index=False)

# Original data ZGH->ENG

Since some Tamazight sentences in the revised dataset were not changed, we don't have to re-translate them.

In [42]:
merged_data = pd.merge(data_original, data_revised, on=["ID"], suffixes=('_original', '_revised'))
merged_data

,ID,eng_original,zgh_original,eng_revised,zgh_revised
0,0,"""We now have 4-month-old mice that are non-dia...","""ⵏⵍⴰ ⴷⵖⵉ ⵉⵖⵔⴷⴰⵢⵏ ⵏ 4 ⵏ ⵉⵢⵢⵉⵔⵏ ⴷ ⵓⵔ ⵉⵍⵍⵉ ⵡⴰⵟⵟⴰⵏ...","""We now have 4-month-old mice that are non-dia...","""ⵍⵍⴰⵏ ⴷⴰⵔ ⵏⵏⵖ ⴷⵖⵉ ⵉⵖⵔⴷⴰⵢⵏ ⵏ 4 ⵡⴰⵢⵢⵓⵔⵏ ⵓⵔ ⵓⴹⵉⵏⵏ..."
1,1,"Dr. Ehud Ur, professor of medicine at Dalhousi...","ⴰⴷⵓⴽⵜⵓⵔ ⵉⵀⵓⵔ ⵓⵔ, ⴰⵙⵍⵎⴰⴷ ⵏ ⵜⴰⵙⵏⵓⵊⵢⴰ ⴳ ⵜⵙⴷⴰⵡⵉⵜ ⵏ...","Dr. Ehud Ur, professor of medicine at Dalhousi...","ⵉⵏⵏⴰ ⵓⴷⵓⴽⵜⵓⵔ ⵉⵀⵓⴷ ⵓⵔ, ⴰⵙⵍⵎⴰⴷ ⵏ ⵜⵙⵏⵉⵊⵊⵉⵜ ⴳ ⵜⵙⴷⴰ..."
2,2,"Like some other experts, he is skeptical about...","ⴰⵎⵎ ⴽⵔ ⵏ ⵡⵉⵢⵢⴰⴹ ⵉⵎⵓⵣⴰⵢⵏ, ⵉⴳⴰ ⴰⵎⵛⴽⴰⴽ ⴳ ⵓⵢⵏⵏⴰ ⵉⵇ...","Like some other experts, he is skeptical about...","ⴰⵎⵎ ⴽⵔⴰ ⵏ ⵉⵎⵓⵣⴰⵢⵏ ⵢⴰⴹⵏⵉⵏ, ⵉⴳⴰ ⴰⵎⵛⴽⴰⴽ ⴳ ⵓⵢⵏⵏⴰ ⵉ..."
3,3,"On Monday, Sara Danius, permanent secretary of...","ⴳ ⵓⵢⵏⴰⵙ, ⵜⵏⵏⴰ ⵚⴰⵕⴰ ⴷⴰⵏⵢⵓⵙ, ⵜⴰⵏⴼⵍⵓⵙⵜ ⵜⴰⵎⵖⵍⴰⵍⵜ ⵏ...","On Monday, Sara Danius, permanent secretary of...","ⴳ ⵓⵢⵏⴰⵙ, ⵜⵏⵏⴰ ⵚⴰⵕⴰ ⴷⴰⵏⵢⵓⵙ, ⵜⴰⵏⴼⵍⵓⵙⵜ ⵜⴰⵎⵖⵍⴰⵍⵜ ⵏ..."
4,4,"Danius said, ""Right now we are doing nothing. ...","ⵜⵏⵏⴰ ⴷⴰⵏⵢⵓⵙ, ""ⴷⵖⵉ ⵓⵔ ⴷⴰ ⵏⵙⵙⴽⴰⵔ ⴰⵎⵢⴰ. ⵖⵔⵉⵖ ⴰⵙ ⴰ...","Danius said, ""Right now we are doing nothing. ...","ⵜⵏⵏⴰ ⴷⴰⵏⵢⵓⵙ, ""ⴷⵖⵉ ⵓⵔ ⴷⴰ ⵏⵙⴽⴰⵔ ⴰⵎⵢⴰ. ⵖⵔⵉⵖ ⴰⵙ ⴰⵣ..."
...,...,...,...,...,...
1007,1007,"As the areas are sparsely populated, and light...","ⵍⵍⵉⴳ ⴷⵔⵓⵙⵏ ⵉⵎⵣⴷⴰⵖⵏ ⴳ ⵜⵎⵏⴰⴹⵜ, ⴷ ⵡⵓⵍⵓⴼ ⵉⴷⵔⵓⵙⵏ ⵛⵉ...","As the areas are sparsely populated, and light...","ⵍⵍⵉⴳ ⴷⵔⵓⵙⵏ ⵉⵎⵣⴷⴰⵖⵏ ⴳ ⵜⵎⵏⴰⴹⵜ, ⴷ ⵡⵓⵍⵓⴼ ⵉⴷⵔⵓⵙⵏ ⵛⵉ..."
1008,1008,Japanese work culture is more hierarchical and...,ⵜⴳⴰ ⵜⴰⴷⵍⵙⴰ ⵏ ⵜⵡⵓⵔⵉ ⵜⴰⵢⴰⴱⴰⵏⵉⵢⵜ ⴷ ⵜⴰⵎⵓⵣⴳⴰⵏⵜ ⵓⴳⴳⴰ...,Japanese work culture is more hierarchical and...,ⵜⴳⴰ ⵜⴰⴷⵍⵙⴰ ⵏ ⵜⵡⵓⵔⵉ ⵜⴰⵢⴰⴱⴰⵏⵉⵢⵜ ⴷ ⵜⴰⵎⵓⵣⴳⴰⵏⵜ ⴷ ⵜⵓ...
1009,1009,"Suits are standard business attire, and cowork...","ⴳⴰⵏ ⵉⴽⵓⵙⵜⵉⵎⵏ ⵜⵉⵎⵍⵙⴰ ⵜⵓⵏⵚⵉⴱⵉⵏ ⵏ ⵉⴷ ⴱⴰⴱ ⵏⵜⵡⵓⵔⵉ, ...","Suits are standard business attire, and cowork...","ⴳⴰⵏ ⵉⴽⵓⵙⵜⵉⵎⵏ ⵜⵉⵎⵍⵙⴰ ⵜⵓⵏⵚⵉⴱⵉⵏ ⵏ ⵉⴷ ⴱⴰⴱ ⵏⵜⵡⵓⵔⵉ, ..."
1010,1010,"Workplace harmony is crucial, emphasizing grou...","ⵜⵙⵜⴰⵡⵀⵎⵎⴰ ⵜⵎⵙⴰⵙⵉⵜ ⵛⵉⴳⴰⵏ ⴳ ⵡⴰⵏⵙ ⵏ ⵜⵡⵓⵔⵉ, ⴰⵔ ⴷ ⵉ...","Workplace harmony is crucial, emphasizing grou...","ⵜⵅⴰⵜⵔ ⴽⵉⴳⴰⵏ ⵜⵎⵙⴰⵙⵉⵜ ⴳ ⵡⴰⵏⵙⴰ ⵏ ⵜⵡⵓⵔⵉ, ⵙ ⵓⵙⵎⵙⵙⵉ ..."
1011,1011,Workers must often get their superiors' approv...,ⵉⴳⴳⵓⵜ ⵎⴰⴳ ⴷ ⵉⵇⵇⴰⵏ ⴰⴷ ⵢⵉⵍⵉ ⵓⵎⵙⴰⵙⴰ ⵏ ⵉⵏⵙⵙⵉⵅⴼⵏ ⵏ ...,Workers must often get their superiors' approv...,ⵉⴳⴳⵓⴷⵉ ⵎⴰ ⴳ ⴷ ⵉⵇⵇⴰⵏ ⴰⴷ ⵢⵉⵍⵉ ⵓⵎⵙⴰⵙⴰ ⵏ ⵉⵏⵙⵙⵉⵅⴼⵏ ...

In [43]:
# Find rows where the original and revised translations differ
diff_rows = merged_data[merged_data['zgh_original'] != merged_data['zgh_revised']]

# Save IDs
diff_ids = diff_rows['ID'].tolist()

diff_rows

,ID,eng_original,zgh_original,eng_revised,zgh_revised
0,0,"""We now have 4-month-old mice that are non-dia...","""ⵏⵍⴰ ⴷⵖⵉ ⵉⵖⵔⴷⴰⵢⵏ ⵏ 4 ⵏ ⵉⵢⵢⵉⵔⵏ ⴷ ⵓⵔ ⵉⵍⵍⵉ ⵡⴰⵟⵟⴰⵏ...","""We now have 4-month-old mice that are non-dia...","""ⵍⵍⴰⵏ ⴷⴰⵔ ⵏⵏⵖ ⴷⵖⵉ ⵉⵖⵔⴷⴰⵢⵏ ⵏ 4 ⵡⴰⵢⵢⵓⵔⵏ ⵓⵔ ⵓⴹⵉⵏⵏ..."
1,1,"Dr. Ehud Ur, professor of medicine at Dalhousi...","ⴰⴷⵓⴽⵜⵓⵔ ⵉⵀⵓⵔ ⵓⵔ, ⴰⵙⵍⵎⴰⴷ ⵏ ⵜⴰⵙⵏⵓⵊⵢⴰ ⴳ ⵜⵙⴷⴰⵡⵉⵜ ⵏ...","Dr. Ehud Ur, professor of medicine at Dalhousi...","ⵉⵏⵏⴰ ⵓⴷⵓⴽⵜⵓⵔ ⵉⵀⵓⴷ ⵓⵔ, ⴰⵙⵍⵎⴰⴷ ⵏ ⵜⵙⵏⵉⵊⵊⵉⵜ ⴳ ⵜⵙⴷⴰ..."
2,2,"Like some other experts, he is skeptical about...","ⴰⵎⵎ ⴽⵔ ⵏ ⵡⵉⵢⵢⴰⴹ ⵉⵎⵓⵣⴰⵢⵏ, ⵉⴳⴰ ⴰⵎⵛⴽⴰⴽ ⴳ ⵓⵢⵏⵏⴰ ⵉⵇ...","Like some other experts, he is skeptical about...","ⴰⵎⵎ ⴽⵔⴰ ⵏ ⵉⵎⵓⵣⴰⵢⵏ ⵢⴰⴹⵏⵉⵏ, ⵉⴳⴰ ⴰⵎⵛⴽⴰⴽ ⴳ ⵓⵢⵏⵏⴰ ⵉ..."
3,3,"On Monday, Sara Danius, permanent secretary of...","ⴳ ⵓⵢⵏⴰⵙ, ⵜⵏⵏⴰ ⵚⴰⵕⴰ ⴷⴰⵏⵢⵓⵙ, ⵜⴰⵏⴼⵍⵓⵙⵜ ⵜⴰⵎⵖⵍⴰⵍⵜ ⵏ...","On Monday, Sara Danius, permanent secretary of...","ⴳ ⵓⵢⵏⴰⵙ, ⵜⵏⵏⴰ ⵚⴰⵕⴰ ⴷⴰⵏⵢⵓⵙ, ⵜⴰⵏⴼⵍⵓⵙⵜ ⵜⴰⵎⵖⵍⴰⵍⵜ ⵏ..."
4,4,"Danius said, ""Right now we are doing nothing. ...","ⵜⵏⵏⴰ ⴷⴰⵏⵢⵓⵙ, ""ⴷⵖⵉ ⵓⵔ ⴷⴰ ⵏⵙⵙⴽⴰⵔ ⴰⵎⵢⴰ. ⵖⵔⵉⵖ ⴰⵙ ⴰ...","Danius said, ""Right now we are doing nothing. ...","ⵜⵏⵏⴰ ⴷⴰⵏⵢⵓⵙ, ""ⴷⵖⵉ ⵓⵔ ⴷⴰ ⵏⵙⴽⴰⵔ ⴰⵎⵢⴰ. ⵖⵔⵉⵖ ⴰⵙ ⴰⵣ..."
...,...,...,...,...,...
1006,1006,This offers a good opportunity to see the Auro...,ⴰⵢⴰ ⵔⴰⴷ ⴰⴽ ⵉⴳ ⴰⵙⵓⵍⴼ ⵏⵏⴰ ⵔⴰⴷ ⵜⴰⵏⵏⴰⵢⴷ Aurora bor...,This offers a good opportunity to see the Auro...,ⴷⴰ ⵢⴰⴽⴽⴰ ⵓⵢⴰ ⵢⴰⵜ ⵜⵎⵍⴷⴰ ⵉⵥⵉⵍⵏ ⵃⵎⴰ ⴰⴷ ⵜⵥⵕⴷ ⵜⵉⴼⴰⵡ...
1008,1008,Japanese work culture is more hierarchical and...,ⵜⴳⴰ ⵜⴰⴷⵍⵙⴰ ⵏ ⵜⵡⵓⵔⵉ ⵜⴰⵢⴰⴱⴰⵏⵉⵢⵜ ⴷ ⵜⴰⵎⵓⵣⴳⴰⵏⵜ ⵓⴳⴳⴰ...,Japanese work culture is more hierarchical and...,ⵜⴳⴰ ⵜⴰⴷⵍⵙⴰ ⵏ ⵜⵡⵓⵔⵉ ⵜⴰⵢⴰⴱⴰⵏⵉⵢⵜ ⴷ ⵜⴰⵎⵓⵣⴳⴰⵏⵜ ⴷ ⵜⵓ...
1009,1009,"Suits are standard business attire, and cowork...","ⴳⴰⵏ ⵉⴽⵓⵙⵜⵉⵎⵏ ⵜⵉⵎⵍⵙⴰ ⵜⵓⵏⵚⵉⴱⵉⵏ ⵏ ⵉⴷ ⴱⴰⴱ ⵏⵜⵡⵓⵔⵉ, ...","Suits are standard business attire, and cowork...","ⴳⴰⵏ ⵉⴽⵓⵙⵜⵉⵎⵏ ⵜⵉⵎⵍⵙⴰ ⵜⵓⵏⵚⵉⴱⵉⵏ ⵏ ⵉⴷ ⴱⴰⴱ ⵏⵜⵡⵓⵔⵉ, ..."
1010,1010,"Workplace harmony is crucial, emphasizing grou...","ⵜⵙⵜⴰⵡⵀⵎⵎⴰ ⵜⵎⵙⴰⵙⵉⵜ ⵛⵉⴳⴰⵏ ⴳ ⵡⴰⵏⵙ ⵏ ⵜⵡⵓⵔⵉ, ⴰⵔ ⴷ ⵉ...","Workplace harmony is crucial, emphasizing grou...","ⵜⵅⴰⵜⵔ ⴽⵉⴳⴰⵏ ⵜⵎⵙⴰⵙⵉⵜ ⴳ ⵡⴰⵏⵙⴰ ⵏ ⵜⵡⵓⵔⵉ, ⵙ ⵓⵙⵎⵙⵙⵉ ..."
1011,1011,Workers must often get their superiors' approv...,ⵉⴳⴳⵓⵜ ⵎⴰⴳ ⴷ ⵉⵇⵇⴰⵏ ⴰⴷ ⵢⵉⵍⵉ ⵓⵎⵙⴰⵙⴰ ⵏ ⵉⵏⵙⵙⵉⵅⴼⵏ ⵏ ...,Workers must often get their superiors' approv...,ⵉⴳⴳⵓⴷⵉ ⵎⴰ ⴳ ⴷ ⵉⵇⵇⴰⵏ ⴰⴷ ⵢⵉⵍⵉ ⵓⵎⵙⴰⵙⴰ ⵏ ⵉⵏⵙⵙⵉⵅⴼⵏ ...

In [44]:
gemini_zgh_eng = pd.read_csv('predictions/gemini-2.5-pro-zgh-eng-revised.csv')
claude_3_5_zgh_eng = pd.read_csv('predictions/claude-3.5-sonnet-20241022-zgh-eng-revised.csv')
claude_3_7_zgh_eng = pd.read_csv('predictions/claude-3.7-sonnet-20250219-zgh-eng-revised.csv')

# Filter the translations to only include rows that were already translated
gemini_zgh_eng_translated = gemini_zgh_eng[~gemini_zgh_eng['ID'].isin(diff_ids)]
claude_3_5_zgh_eng_translated = claude_3_5_zgh_eng[~claude_3_5_zgh_eng['ID'].isin(diff_ids)]
claude_3_7_zgh_eng_translated = claude_3_7_zgh_eng[~claude_3_7_zgh_eng['ID'].isin(diff_ids)]

# Save the translations to CSV files
gemini_zgh_eng_translated.to_csv("predictions/gemini-2.5-pro-zgh-eng-original.csv", index=False)
claude_3_5_zgh_eng_translated.to_csv("predictions/claude-3.5-sonnet-20241022-zgh-eng-original.csv", index=False)
claude_3_7_zgh_eng_translated.to_csv("predictions/claude-3.7-sonnet-20250219-zgh-eng-original.csv", index=False)

In [45]:
answers = await get_llm_answers_async(data_original, "openrouter/google/gemini-2.5-pro", "zgh", "eng", resume_from="predictions/gemini-2.5-pro-zgh-eng-original.csv", max_in_flight_requests=10, temperature=0.0, max_completion_tokens=25000, num_retries=2)
answers

Resuming from predictions/gemini-2.5-pro-zgh-eng-original.csv
Found 673 previously processed rows
Processing 339 new rows

        ID                                         prediction
673      0  "We have 4-month-old mice here, and there is n...
674      1  Dr. Ihor Hur, a professor of medicine at Dalho...
675      2  Like all other researchers, he is skeptical ab...
676      3  On Monday, Sara Danius, the permanent secretar...
677      4  Danyus said, "That's not how we do things here...
...    ...                                                ...
672   1007  When the population in the region is sparse an...
1008  1008  Japanese work culture is more disciplined and ...
1009  1009  Uniforms are the official attire of employers,...
1010  1010  Collaboration is very important in the workpla...
1011  1011  It is very important that the workers' leaders...

[1012 rows x 2 columns]

In [46]:
# save the answers to a CSV file
answers.to_csv("predictions/gemini-2.5-pro-zgh-eng-original.csv", index=False)

In [47]:
answers = await get_llm_answers_async(data_original, "anthropic/claude-3-5-sonnet-20241022", "zgh", "eng", resume_from="predictions/claude-3.5-sonnet-20241022-zgh-eng-original.csv", max_in_flight_requests=4, temperature=0.0, num_retries=2)
answers

Resuming from predictions/claude-3.5-sonnet-20241022-zgh-eng-original.csv
Found 673 previously processed rows
Processing 339 new rows

        ID                                         prediction
673      0  "We now have 4-month-old mice and they don't h...
674      1  Dr. Ihour Ur, a psychology professor at Dalhou...
675      2  Like other researchers, he is skeptical about ...
676      3  On Tuesday, Sara Danius, the permanent secreta...
677      4  Danyus said, "Now we don't do that anymore. I ...
...    ...                                                ...
672   1007  When there are few inhabitants in the region, ...
1008  1008  Japanese work culture is more hierarchical and...
1009  1009  The suits are the official clothes of employer...
1010  1010  Cooperation is very important in the workplace...
1011  1011  It is necessary that there be agreement betwee...

[1012 rows x 2 columns]

In [48]:
# save the answers to a CSV file
answers.to_csv("predictions/claude-3.5-sonnet-20241022-zgh-eng-original.csv", index=False)

In [49]:
answers = await get_llm_answers_async(data_original, "anthropic/claude-3-7-sonnet-20250219", "zgh", "eng", resume_from="predictions/claude-3.7-sonnet-20250219-zgh-eng-original.csv", max_in_flight_requests=3, max_completion_tokens=25000, reasoning_effort="medium", num_retries=2)
answers

Resuming from predictions/claude-3.7-sonnet-20250219-zgh-eng-original.csv
Found 673 previously processed rows
Processing 339 new rows

        ID                                         prediction
673      0  "We now have mice that are 4 months old and th...
674      1  Dr. Ihour Ur, a professor of psychology at Dal...
675      2  Like other researchers, he is skeptical about ...
676      3  On Tuesday, Sara Danius, the permanent secreta...
677      4  Danyus said, "Nowadays we don't do this anymor...
...    ...                                                ...
672   1007  When there are few inhabitants in the region, ...
1008  1008  Japanese work culture is more disciplined and ...
1009  1009  Suits are the official attire of employers, an...
1010  1010  Cooperation in the workplace is very important...
1011  1011  It is often necessary that there be agreement ...

[1012 rows x 2 columns]

In [50]:
# save the answers to a CSV file
answers.to_csv("predictions/claude-3.7-sonnet-20250219-zgh-eng-original.csv", index=False)